/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://ekz2req7xvevnmxi5ph6napxwu.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2ca7dm3zbnbtfjubqywle642wm",
    "aws_cognito_identity_pool_id": "us-west-1:094a591c-591a-4b6c-a5bd-b8cf530cb8b3",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_UMbgoifbJ",
    "aws_user_pools_web_client_id": "2r7uhrqf9v57f6htcohrma6eu2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "penrynflowerfarmbucket195050-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
